export const copy = {
  es: {
    nav: {
      links: [
        { label: 'Nosotros', href: '#nosotros' },
        { label: 'Mosaico™', href: '#mosaico' },
        { label: 'Proceso', href: '#fases' },
        { label: 'Contacto', href: '#contacto' },
      ],
      cta: 'Solicitar Mosaico™',
    },
    hero: {
      kicker: 'Para gerentes que exigen control total sobre sus márgenes',
      headline: ['En 14 días, con los datos que ya tienen, le decimos exactamente cuánto', 'está perdiendo su empresa — y por qué.'],
      sub: 'Sin implementaciones largas. Sin dashboards que nadie lee. Solo un número y un plan: tres tácticas para recuperar el margen — al final de los 14 días.',
      ctaPrimary: 'Solicitar el Mosaico™ — Diagnóstico de 14 Días',
      ctaSecondary: 'Ver Casos de Estudio',
    },
    manifesto: {
      label: 'Quiénes somos',
      title: 'Nosotros también estuvimos ahí.',
      p1: 'Durante años, trabajamos desde adentro de las firmas que tenían las mejores herramientas del mundo — McKinsey, Meta, Experian. Vimos cómo se diseñan los flujos de información que controlan los ingresos de las organizaciones más complejas del mercado.',
      p2: 'Pero también vimos la falla estructural de la consultoría tradicional. Las grandes metodologías y los sistemas de inteligencia de negocios están diseñados para corporaciones con presupuestos infinitos y años de sobra para implementar software.',
      p3: 'Las empresas medianas en LATAM tienen los mismos problemas operacionales — y la misma urgencia de resolverlos. Lo que no tienen es tiempo ni disposición para un engagement de 18 meses que entrega un reporte al final. E5 existe para eso.',
      p4: 'En Centroamérica y LATAM, las reglas son distintas. Las empresas tienen la misma complejidad operativa y los mismos problemas de fuga de margen que un Fortune 500, pero no tienen el lujo de esperar 6 o 12 meses por un reporte teórico. Necesitan una intervención diseñada específicamente para su escala, su velocidad, y su realidad de datos.',
      p4Bold: 'Con lo que ya tienen hoy.',
      cta: 'Hablemos de su operación',
    },
    mosaico: {
      label: 'El Diagnóstico',
      subtitle: 'Mosaico™: Lo que su operación ya sabe — y usted todavía no.',
      title: 'Ponga un espejo frente a su operación en 14 días. Con la información que ya tiene hoy.',
      intro: 'El diagnóstico integral Mosaico™ es una intervención clínica de dos semanas sobre sus sistemas actuales. No requerimos datos nuevos, servidores nuevos ni cambios de infraestructura. Mapeamos con precisión quirúrgica las tres brechas donde la intuición le está costando dinero hoy:',
      gaps: [
        {
          number: '01',
          title: 'El producto que parece premium puede no ser el más rentable.',
          body: 'Desmantelamos la intuición del equipo de ventas demostrando el margen real neto por modalidad después de royalties, mermas y costos operativos ocultos. Le mostramos matemáticamente si su supuesto motor de ingresos en realidad está subsidiando pérdidas.',
        },
        {
          number: '02',
          title: 'Las cuentas que sostienen el negocio no tienen protección activa.',
          body: 'Construimos sistemas de alerta temprana a nivel de datos para identificar la erosión o riesgo de fuga de sus cuentas corporativas de alto valor antes de que muestren señales de salida silenciosa. Para cuando se dan cuenta de que se van, ya es tarde.',
        },
        {
          number: '03',
          title: 'Las decisiones más costosas se toman sin datos.',
          body: 'Reemplazamos el impulso ejecutivo por un número exacto antes de que comprometa costos fijos altos en aperturas, cierres o contrataciones. Decisiones que tardan años en manifestarse en los libros del negocio.',
        },
      ],
      guaranteeLabel: 'La Garantía E5',
      guarantee: 'Al final de los 14 días, su equipo recibe un número exacto y tres tácticas para recuperar margen neto. Al salir del Mosaico™, usted tiene un número. No un reporte de 80 páginas. Un número exacto por canal, por producto, por sucursal. Y tres tácticas listas para ejecutarse al día siguiente del diagnóstico.',
      cta: 'Solicitar el Mosaico™ — Diagnóstico de 14 Días',
    },
    phases: {
      label: 'El Arco Completo',
      title: 'El Día 14 Es Donde Empieza el Trabajo Real.',
      intro: 'Para el día 14, usted tiene un número. Pero el número es la parte fácil. Lo difícil es lo que ese número revela: que su organización lleva tiempo decidiendo con información incompleta. Eso no se arregla con un reporte. Es un problema de sofisticación organizacional.',
      intro2: 'El Mosaico™ es la entrada a un arco de cinco fases. Usted avanza al ritmo que su organización necesita.',
      items: [
        { phase: 'Examine', tag: 'Mosaico™ Assessment · 14 días', desc: 'Ve exactamente cuánto está perdiendo y dónde.' },
        { phase: 'Engineer', tag: '4–6 semanas', desc: 'Diseñamos la intervención sobre la brecha más cara que el diagnóstico expuso.' },
        { phase: 'Execute', tag: '3–6 meses', desc: 'Implementamos. Su equipo ve los efectos en el P&L, no en un dashboard.' },
        { phase: 'Elevate', tag: 'Continuo', desc: 'Rediseñamos cómo decide la organización, no solo qué decide.' },
        { phase: 'Evolve', tag: 'Advisory', desc: 'Su equipo opera con autonomía. Nosotros entramos solo en momentos estratégicos.' },
      ],
      closing: 'La mayoría de nuestros clientes empieza con el Mosaico™ y decide desde ahí. Quienes obtienen el mayor retorno tratan el diagnóstico por lo que es: la puerta, no el destino.',
    },
    contact: {
      label: 'Siguiente Paso',
      title: 'Hablemos de su operación.',
      sub: 'Cuéntenos brevemente qué está pasando en su empresa. Evaluaremos su caso para confirmar si el Mosaico™ es la intervención adecuada para sus sistemas actuales.',
      bullets: ['14 días', 'Proyecto a precio fijo', 'Sin cambios de infraestructura requeridos'],
      question: '¿Cuál es el reto principal de visibilidad de datos en su operación hoy?',
      namePlaceholder: 'Nombre completo',
      emailPlaceholder: 'Correo corporativo',
      companyPlaceholder: 'Empresa',
      submit: 'Solicitar el Mosaico™',
      successTitle: 'Recibido.',
      successSub: 'Evaluaremos su caso y le contactaremos pronto.',
    },
    pageTitle: 'E5 Modular — Diagnóstico de operaciones en 14 días para empresas en LATAM',
    footer: {
      tagline: 'En 14 días, con los datos que tienen, le decimos exactamente cuánto están perdiendo — y por qué.',
      rights: '© 2026 E5 Modular. Todos los derechos reservados.',
    },
  },

  en: {
    nav: {
      links: [
        { label: 'About', href: '#nosotros' },
        { label: 'Mosaico™', href: '#mosaico' },
        { label: 'Process', href: '#fases' },
        { label: 'Contact', href: '#contacto' },
      ],
      cta: 'Get the Mosaico™',
    },
    hero: {
      kicker: 'For Managers Who Demand Total Control Over Their Margins',
      headline: ['In 14 days, with the data you already have, we tell you exactly', 'how much your company is losing — and why.'],
      sub: 'No long implementations. No dashboards nobody reads. Just a number and a plan: three tactics to recover margin — delivered at the end of 14 days.',
      ctaPrimary: 'Request the Mosaico™ — 14-Day Diagnostic',
      ctaSecondary: 'View Case Studies',
    },
    manifesto: {
      label: 'Who We Are',
      title: 'We\'ve Been There Too.',
      p1: 'During years inside the firms with the best tools in the world — McKinsey, Meta, Experian — we watched how data flows control revenue at the most complex organizations.',
      p2: 'But we also saw the structural failure of traditional consulting. The best methodologies and business intelligence systems are designed for corporations with infinite budgets and years to spare implementing software.',
      p3: '',
      p4: 'In Central America and LATAM, the rules are different. Companies have the same operational complexity and the same margin leak problems as a Fortune 500, but they don\'t have the luxury of waiting 6 or 12 months for a theoretical report. They need an intervention designed specifically for their scale, their speed, and their data reality.',
      p4Bold: 'With what they already have today.',
      cta: 'Let\'s Talk About Your Operation',
    },
    mosaico: {
      label: 'The Diagnostic',
      subtitle: 'Mosaico™: What Your Operation Already Knows — And You Don\'t Yet.',
      title: 'Hold a Mirror to Your Operation in 14 Days. With the Information You Already Have.',
      intro: 'The Mosaico™ assessment is a clinical two-week intervention on your existing systems. We don\'t require new data, new servers, or infrastructure changes. We map with surgical precision the three gaps where intuition is costing you money today:',
      gaps: [
        {
          number: '01',
          title: 'The Product That Looks Premium May Not Be Your Most Profitable.',
          body: 'We dismantle your sales team\'s intuition by proving actual net margin by offering after royalties, waste, and hidden operating costs. We show you mathematically whether your supposed revenue engine is actually subsidizing losses.',
        },
        {
          number: '02',
          title: 'The Accounts Sustaining the Business Have No Active Protection.',
          body: 'We build early-warning systems at the data level to identify erosion or flight risk in your high-value corporate accounts before they show silent exit signals. By the time you notice they\'re leaving, it\'s too late.',
        },
        {
          number: '03',
          title: 'The Most Expensive Decisions Are Made Without Data.',
          body: 'We replace executive impulse with an exact number before you commit to high fixed costs in openings, closures, or hires. Decisions that take years to show up on the books.',
        },
      ],
      guaranteeLabel: 'The E5 Guarantee',
      guarantee: 'At the end of 14 days, your team receives one exact number and three tactics to recover net margin. When you exit the Mosaico™, you have a number. Not an 80-page report. One exact number — by channel, by product, by location — and three tactics ready to execute the day after the diagnostic ends.',
      cta: 'Request the Mosaico™ — 14-Day Diagnostic',
    },
    phases: {
      label: 'The Full Arc',
      title: 'Day 14 Is Where the Real Work Begins.',
      intro: 'By day 14, you have a number. But the number is the easy part. The hard part is what that number reveals: that your organization has been making decisions with incomplete information for a while. That doesn\'t get fixed with a report. It\'s an organizational sophistication problem.',
      intro2: 'The Mosaico™ is the entry to a five-phase arc. You move at the pace your organization needs.',
      items: [
        { phase: 'Examine', tag: 'Mosaico™ Assessment · 14 days', desc: 'You see exactly how much you\'re losing and where.' },
        { phase: 'Engineer', tag: '4–6 weeks', desc: 'We design the intervention targeting the most expensive gap the diagnostic exposed.' },
        { phase: 'Execute', tag: '3–6 months', desc: 'We implement. Your team sees the effects in the P&L, not in a dashboard.' },
        { phase: 'Elevate', tag: 'Ongoing', desc: 'We redesign how the organization makes decisions, not just what it decides.' },
        { phase: 'Evolve', tag: 'Advisory', desc: 'Your team operates autonomously. We come in only at strategic moments.' },
      ],
      closing: 'Most of our clients start with the Mosaico™ and decide from there. Those who get the highest return treat the diagnostic for what it is: the door, not the destination.',
    },
    contact: {
      label: 'Next Step',
      title: 'Let\'s Talk About Your Operation.',
      sub: 'Tell us briefly what\'s happening in your company. We\'ll evaluate your case to confirm whether the Mosaico™ is the right intervention for your current systems.',
      bullets: ['14 days', 'Fixed-price project', 'No new systems or infrastructure changes'],
      question: 'What is the main data visibility challenge in your operation today?',
      namePlaceholder: 'Full name',
      emailPlaceholder: 'Corporate email',
      companyPlaceholder: 'Company',
      submit: 'Get the Mosaico™',
      successTitle: 'Received.',
      successSub: 'We\'ll evaluate your case and be in touch soon.',
    },
    pageTitle: 'E5 Modular — Operational diagnostics in 14 days for companies in LATAM',
    footer: {
      tagline: 'In 14 days, with the data you have, we tell you exactly how much you\'re losing — and why.',
      rights: '© 2026 E5 Modular. All rights reserved.',
    },
  },
}
