export const copy = {
  es: {
    nav: {
      links: [
        { label: 'Nosotros', href: '#nosotros' },
        { label: 'Mosaico™', href: '#mosaico' },
        { label: 'Proceso', href: '#fases' },
        { label: 'Contacto', href: '#contacto' },
      ],
      cta: 'Solicitar Mosaico™',
    },
    hero: {
      kicker: 'Para CXOs que miden lo que realmente se pierde',
      headline: ['En 14 días, con los datos que ya tienen, le decimos exactamente cuánto', 'está perdiendo su empresa — y por qué.'],
      sub: 'Sin proyectos eternos de TI. Sin software nuevo. Sin tableros que nadie lee. Solo un número real y dos acciones ejecutables para recuperar margen desde la primera semana.',
      ctaPrimary: 'Solicitar el Mosaico™ — 14 Días, Precio Fijo ($3K–$5K)',
      ctaSecondary: 'Ver Casos de Estudio',
    },
    manifesto: {
      label: 'Quiénes somos',
      title: 'Nosotros también estuvimos ahí.',
      p1: 'Durante años, trabajamos desde adentro de las firmas que tenían las mejores herramientas del mundo — McKinsey, Meta, Gensler. Vimos cómo se diseñan los flujos de información que controlan los ingresos de las organizaciones más complejas del mercado.',
      p2: 'Trabajamos con empresas que tenían el potencial real de crecer pero no calificaban para recibir asesoría directa — su nivel de inversión no llegaba al umbral que lo habilitaba. Estaban atrapadas en una paradoja: necesitaban la sofisticación para escalar, pero no podían acceder a ella hasta que ya hubieran escalado.',
      p3: 'Y desde otra industria, el mismo patrón: las mejores metodologías de diagnóstico operacional eran estándar en mercados desarrollados, pero prohibitivamente caras en LATAM. El mercado que más las necesitaba era el que menos podía acceder a ellas.',
      p4: 'No salimos a competir con McKinsey ni con Meta. Salimos a construir para el mercado que ellos no pueden servir: las empresas medianas en Centroamérica y LATAM que tienen los mismos problemas operacionales que las corporaciones Fortune 500, pero que necesitan una intervención diseñada específicamente para su escala, su velocidad, y su realidad de datos.',
      p4Bold: 'Con lo que ya tienen hoy.',
      cta: 'Hablemos de su operación',
    },
    mosaico: {
      label: 'El Diagnóstico',
      title: 'Ponle un espejo a tu operación en 14 días. Con los datos que ya tenés hoy.',
      intro: 'El Mosaico™ Assessment es una intervención clínica de dos semanas sobre sus sistemas actuales. No requerimos datos nuevos, servidores nuevos ni cambios de infraestructura. Mapeamos con precisión quirúrgica las tres brechas donde la intuición le está costando dinero hoy:',
      gaps: [
        {
          number: '01',
          title: 'El producto que parece premium puede no ser el más rentable.',
          body: 'Desmantelamos la intuición del equipo de ventas demostrando el margen real neto por modalidad después de royalties y costos operativos ocultos. Lo que creían que era su motor de ingresos puede no serlo.',
        },
        {
          number: '02',
          title: 'Las cuentas que sostienen el negocio no tienen protección activa.',
          body: 'Clasificamos y blindamos contractualmente sus cuentas corporativas de alto valor antes de que muestren señales de salida silenciosa. Para cuando se dan cuenta de que se van, ya es tarde.',
        },
        {
          number: '03',
          title: 'Las decisiones más costosas se toman sin datos.',
          body: 'Reemplazamos el impulso ejecutivo por un número exacto antes de que comprometa costos fijos altos en aperturas, cierres o contrataciones. Decisiones que tardan años en manifestarse en los libros del negocio.',
        },
      ],
      guaranteeLabel: 'La Garantía E5',
      guarantee: 'En la segunda semana de la intervención, su equipo recibe las primeras dos acciones visibles y ejecutables para recuperar margen neto. Al salir del Mosaico™, usted tiene un número. No un reporte de 80 páginas. Un número exacto por canal, por producto, por sucursal. Y dos acciones para empezar a recuperarlo la semana siguiente.',
      cta: 'Solicitar el Mosaico™ — 14 Días, Precio Fijo ($3K–$5K)',
    },
    phases: {
      label: 'El Arco Completo',
      title: 'El Día 14 Es Donde Empieza el Trabajo Real.',
      intro: 'Para el día 14, usted tiene un número. Pero el número es la parte fácil. Lo difícil es lo que ese número revela: que su organización lleva tiempo decidiendo con información incompleta. Eso no se arregla con un reporte. Es un problema de sofisticación organizacional.',
      intro2: 'El Mosaico™ es la entrada a un arco de cinco fases. Usted avanza al ritmo que su organización necesita.',
      items: [
        { phase: 'Examine', tag: 'Mosaico™ Assessment · 14 días', desc: 'Ve exactamente cuánto está perdiendo y dónde.' },
        { phase: 'Engineer', tag: '4–6 semanas', desc: 'Diseñamos la intervención sobre la brecha más cara que el diagnóstico expuso.' },
        { phase: 'Execute', tag: '3–6 meses', desc: 'Implementamos. Su equipo ve los efectos en el P&L, no en un dashboard.' },
        { phase: 'Elevate', tag: 'Continuo', desc: 'Rediseñamos cómo decide la organización, no solo qué decide.' },
        { phase: 'Evolve', tag: 'Advisory', desc: 'Su equipo opera con autonomía. Nosotros entramos solo en momentos estratégicos.' },
      ],
      closing: 'La mayoría de nuestros clientes empieza con el Mosaico™ y decide desde ahí. Quienes obtienen el mayor retorno tratan el diagnóstico por lo que es: la puerta, no el destino.',
    },
    contact: {
      label: 'Siguiente Paso',
      title: 'Hablemos de su operación.',
      sub: 'Cuéntenos brevemente qué está pasando en su empresa. Le respondemos en menos de 24 horas.',
      question: '¿Cuál es el reto principal de visibilidad de datos en su operación hoy?',
      namePlaceholder: 'Nombre completo',
      emailPlaceholder: 'Correo corporativo',
      companyPlaceholder: 'Empresa',
      submit: 'Solicitar el Mosaico™',
      note: 'Proyecto a precio fijo. Sin cambios de infraestructura requeridos.',
    },
    footer: {
      tagline: 'En 14 días, con los datos que tienen, le decimos exactamente cuánto están perdiendo — y por qué.',
      rights: '© 2026 E5 Modular. Todos los derechos reservados.',
    },
  },

  en: {
    nav: {
      links: [
        { label: 'About', href: '#nosotros' },
        { label: 'Mosaico™', href: '#mosaico' },
        { label: 'Process', href: '#fases' },
        { label: 'Contact', href: '#contacto' },
      ],
      cta: 'Get the Mosaico™',
    },
    hero: {
      kicker: 'For CXOs Who Know Exactly What\'s Leaking',
      headline: ['In 14 days, with the data you already have, we tell you exactly', 'how much your company is losing — and why.'],
      sub: 'No eternal IT projects. No new software. No dashboards nobody reads. Just a real number and two executable actions to recover margin from day one.',
      ctaPrimary: 'Get the Mosaico™ — 14-Day Diagnostic, Fixed Price ($3K–$5K)',
      ctaSecondary: 'View Case Studies',
    },
    manifesto: {
      label: 'Who We Are',
      title: 'We\'ve Been There Too.',
      p1: 'During years inside the firms with the best tools in the world — McKinsey, Meta, Gensler — we watched how data flows control revenue at the most complex organizations.',
      p2: 'We worked with companies that had real potential to grow but didn\'t qualify for direct advisory — their investment level didn\'t hit the threshold that unlocked it. They were trapped in a paradox: they needed sophistication to scale, but couldn\'t access it until they\'d already scaled.',
      p3: 'And from another industry, the same pattern: the best operational diagnostic methodologies were standard in developed markets, but prohibitively expensive in LATAM. The market that needed them most was the one that could least afford them.',
      p4: 'We didn\'t set out to compete with McKinsey or Meta. We set out to build for the market they can\'t serve: mid-market companies in Central America and LATAM with the same operational problems as Fortune 500s, but who need an intervention designed for their scale, speed, and data reality.',
      p4Bold: 'With what they already have.',
      cta: 'Let\'s Talk About Your Operation',
    },
    mosaico: {
      label: 'The Diagnostic',
      title: 'Put a Mirror to Your Operation in 14 Days. With the Data You Already Have.',
      intro: 'The Mosaico™ Assessment is a clinical two-week intervention on your existing systems. We don\'t require new data, new servers, or infrastructure changes. We map with surgical precision the three gaps where intuition is costing you money today:',
      gaps: [
        {
          number: '01',
          title: 'The Product That Looks Premium May Not Be Your Most Profitable.',
          body: 'We dismantle your sales team\'s intuition by proving actual net margin by offering after royalties and hidden operating costs. What they thought was their revenue engine may not be.',
        },
        {
          number: '02',
          title: 'The Accounts Sustaining the Business Have No Active Protection.',
          body: 'We classify and contractually shield your high-value corporate accounts before they show silent exit signals. By the time you notice they\'re leaving, it\'s too late.',
        },
        {
          number: '03',
          title: 'The Most Expensive Decisions Are Made Without Data.',
          body: 'We replace executive impulse with an exact number before you commit to high fixed costs in openings, closures, or hires. Decisions that take years to show up on the books.',
        },
      ],
      guaranteeLabel: 'The E5 Guarantee',
      guarantee: 'In the second week of the intervention, your team gets the first two visible, executable actions to recover net margin. When you exit the Mosaico™, you have a number. Not an 80-page report. One exact number — by channel, by product, by location — and two actions to start recovering it the following week.',
      cta: 'Get the Mosaico™ — 14 Days, Fixed Price ($3K–$5K)',
    },
    phases: {
      label: 'The Full Arc',
      title: 'Day 14 Is Where the Real Work Begins.',
      intro: 'By day 14, you have a number. But the number is the easy part. The hard part is what that number reveals: that your organization has been making decisions with incomplete information for a while. That doesn\'t get fixed with a report. It\'s an organizational sophistication problem.',
      intro2: 'The Mosaico™ is the entry to a five-phase arc. You move at the pace your organization needs.',
      items: [
        { phase: 'Examine', tag: 'Mosaico™ Assessment · 14 days', desc: 'You see exactly how much you\'re losing and where.' },
        { phase: 'Engineer', tag: '4–6 weeks', desc: 'We design the intervention targeting the most expensive gap the diagnostic exposed.' },
        { phase: 'Execute', tag: '3–6 months', desc: 'We implement. Your team sees the effects in the P&L, not in a dashboard.' },
        { phase: 'Elevate', tag: 'Ongoing', desc: 'We redesign how the organization makes decisions, not just what it decides.' },
        { phase: 'Evolve', tag: 'Advisory', desc: 'Your team operates autonomously. We come in only at strategic moments.' },
      ],
      closing: 'Most of our clients start with the Mosaico™ and decide from there. Those who get the highest return treat the diagnostic for what it is: the door, not the destination.',
    },
    contact: {
      label: 'Next Step',
      title: 'Let\'s Talk About Your Operation.',
      sub: 'Tell us briefly what\'s happening in your company. We\'ll respond in under 24 hours.',
      question: 'What is the main data visibility challenge in your operation today?',
      namePlaceholder: 'Full name',
      emailPlaceholder: 'Corporate email',
      companyPlaceholder: 'Company',
      submit: 'Get the Mosaico™',
      note: 'Fixed-price project. No infrastructure changes required.',
    },
    footer: {
      tagline: 'In 14 days, with the data you have, we tell you exactly how much you\'re losing — and why.',
      rights: '© 2026 E5 Modular. All rights reserved.',
    },
  },
}
